Update isOffline(errorCode:) to catch additional NSURLError
openfoodfacts/openfoodfacts-ios pull request #710
Opened 2020-08-11 19:57 UTC by jncosideout

## PR Description

The app is not saving scanned barcodes when offline/no internet connectivity.

I tested the offline scan by setting my device to airplane mode and scanning a food product.
This throws to the ```onError``` callback (line 442) of ```dataManager.getProduct(byBarcode:)``` inside ```ScannerViewController.getProduct(barcode: ...)```

The next line checks ```isOffline(errorCode:)``` and if true, we call ```handleGetProductSuccess(barcode: ...)```
According to the comment in the source code, this is when we:
```//Assume product does not exist and store locally for later upload```

For me, the error code passed is -1004 "Could not connect to the server." According to my research, that matches [NSURLErrorCannotConnectToHost](https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorcannotconnecttohost)

**My only concern** is that there are other NSURLErrors or other errors that would be thrown when offline or when connectivity is bad. isOffline(errorCode:) should anticipate all possible such error codes.

## Type of Changes 

- [x] Fixes Issue #267 
- [ ] New feature

## Checklist
  
 - [ ] If you have multiple commits please combine them into one commit by [squashing](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) them. 
 - [ ] Code is well documented
 - [ ] Included unit tests for new functionality
 - [ ] All user-visible strings are made translatable
 - [ ] Code passes Travis builds in your branch

2020-08-12 07:48 UTC, philippeauriach requested changes
As we are touching those, we might want to add more cases to "no internet connection" test ?
The full list of errors is listed here : https://developer.apple.com/documentation/cfnetwork/cfnetworkerrors

I think we should go for those (open to discussion) : 
kCFURLErrorCannotFindHost
kCFURLErrorCannotConnectToHost
kCFURLErrorNetworkConnectionLost
kCFURLErrorDNSLookupFailed
kCFURLErrorInternationalRoamingOff
kCFURLErrorCallIsActive
kCFURLErrorDataNotAllowed

2020-08-12 17:05 UTC, jncosideout commented
> As we are touching those, we might want to add more cases to "no internet connection" test ?
I think that is a exactly what I'm thinking. I will include them into ```isOffline(errorCode:)``` and re-submit my PR.

I checked the CFNetworkErrors you listed, each one corresponds to an NSURLError and they have the same raw values. 
Therefore, I shouldn't need to re-cast the error into a CFNetworkError before passing them to ```isOffline(errorCode:)```

But how do I test those scenarios to throw the particular errors? Most of them seem out of my control so I don't know how to replicate them, e.g. "CannotFindHost", "InternationalRoamingOff", "CannotConnectToHost"

Also, my testing devices do not have cellular plans. So they're WiFi only.

2020-08-14 23:32 UTC, jncosideout commented
I wasn't able to trigger all the newly included network errors while testing, but I can confirm that ```func isOffline(:errorCode)``` will recognize when the device has no connection to the internet, because the error that is thrown when the device in airplane mode (CannotConnectToHost -1004) has been included.

2020-08-17 10:17 UTC, philippeauriach approved these changes

2020-08-19 15:02 UTC, merged

2020-08-19 15:02 UTC, teolemon commented
Thank you @jncosideout and @philippeauriach for the review 👍